// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eazdydzcwilqpbgngxni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhemR5ZHpjd2lscXBiZ25neG5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjgyOTgsImV4cCI6MjA2OTcwNDI5OH0.x8HCzYMme1Um28Jo1vCM74jq53SKJQpV-XQ46ER2JWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});